spring:
  application:
    name: processor
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: inventory-processor-group
      auto-offset-reset: earliest
    streams:
      application-id: inventory-streams-app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: com.inventory.stream.serdes.JsonSerde
